SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS PAPERS;
DROP TABLE IF EXISTS STATE;
DROP TABLE IF EXISTS CITY;
DROP TABLE IF EXISTS UNIVERSITIES;
DROP TABLE IF EXISTS COLLEGES;
DROP TABLE IF EXISTS DEPARTMENT;
DROP TABLE IF EXISTS ADMISSIONS;
DROP TABLE IF EXISTS ADMISSIONS_MATERIAL;
DROP TABLE IF EXISTS LIVING_COST;
DROP TABLE IF EXISTS PAPER_FOCUS;
DROP TABLE IF EXISTS FACULTY;
DROP TABLE IF EXISTS PUBLISH;
DROP TABLE IF EXISTS INTEREST_FIELDS;
DROP TABLE IF EXISTS PROGRAM;
DROP TABLE IF EXISTS RESEARCH_INTERNSHIP;
DROP TABLE IF EXISTS TA_OPTION;
DROP TABLE IF EXISTS MASTERS;
DROP TABLE IF EXISTS MASTERS_PROJECTS;
DROP TABLE IF EXISTS PHD;
DROP TABLE IF EXISTS PHD_PROJECTS;

DROP TABLE IF EXISTS COURSE;
DROP TABLE IF EXISTS PREREQUISITE;
DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS GRADE_REPORT;
DROP TABLE IF EXISTS SECTION;

SET FOREIGN_KEY_CHECKS = 1;