CREATE TABLE PAPERS
	(citation VARCHAR(400) NOT NULL,
	pName VARCHAR(200) NOT NULL,
	PRIMARY KEY (citation));

CREATE TABLE STATE 
	(sName VARCHAR(2) NOT NULL,
	usREGION VARCHAR(10) NOT NULL,
	PRIMARY KEY (sName));

CREATE TABLE CITY
	(cName VARCHAR(15) NOT NULL,
	enHazards BOOLEAN,
	popSize INT,
	popDensity REAL,
	crimePerCapita REAL,
	stateName VARCHAR(2) NOT NULL,
	PRIMARY KEY (cName),
	FOREIGN KEY (stateName) REFERENCES STATE(sName));

CREATE TABLE UNIVERSITIES
	(uName VARCHAR(40) NOT NULL,
	size INT,
	public BOOLEAN,
	inState INT,
	outState INT,
	researchClass VARCHAR(2),
	cityName VARCHAR(15) NOT NULL,
	PRIMARY KEY (uName),
	FOREIGN KEY (cityName) REFERENCES CITY(cName));

CREATE TABLE DEPARTMENT
	(unName VARCHAR(40) NOT NULL,
	dName VARCHAR(50) NOT NULL,
	PRIMARY KEY (unName, dName),
	FOREIGN KEY (unName) REFERENCES UNIVERSITIES(uName));

CREATE TABLE ADMISSIONS
	(uName VARCHAR(40) NOT NULL,
	appPrice INT,
	rollingStat BOOLEAN,
	fallDeadline DATE,
	PRIMARY KEY (uName),
	FOREIGN KEY (uName) REFERENCES UNIVERSITIES(uName));

CREATE TABLE ADMISSIONS_MATERIAL
	(uName VARCHAR(40) NOT NULL,
	material VARCHAR(25) NOT NULL,
	PRIMARY KEY (uName, material),
	FOREIGN KEY (uName) REFERENCES ADMISSIONS(uName));

CREATE TABLE LIVING_COST 
	(cityName VARCHAR(15) NOT NULL,
	gasPrice REAL,
	studioRent REAL,
	PRIMARY KEY (cityName),
	FOREIGN KEY (cityName) REFERENCES CITY(cName));

CREATE TABLE PAPER_FOCUS
	(citation VARCHAR(400) NOT NULL,
	focus VARCHAR(40),
	PRIMARY KEY (citation, focus),
	FOREIGN KEY (citation) REFERENCES PAPERS(citation));

CREATE TABLE FACULTY
	(email VARCHAR(40) NOT NULL,
	firstn VARCHAR(15) NOT NULL,
	lastn VARCHAR(15) NOT NULL,
	uniName VARCHAR(40) NOT NULL,
	dName VARCHAR(50) NOT NULL,
	PRIMARY KEY (email),
	FOREIGN KEY (uniName) REFERENCES UNIVERSITIES(uName),
	FOREIGN KEY (uniName, dName) REFERENCES DEPARTMENT(unName, dName));

CREATE TABLE PUBLISH 
	(citation VARCHAR(400) NOT NULL,
	email VARCHAR(40) NOT NULL,
	PRIMARY KEY (citation, email),
	FOREIGN KEY (citation) REFERENCES PAPERS(citation),
	FOREIGN KEY (email) REFERENCES FACULTY(email));

CREATE TABLE INTEREST_FIELDS
	(email VARCHAR(40) NOT NULL,
	interest VARCHAR(30),
	PRIMARY KEY (email, interest),
	FOREIGN KEY (email) REFERENCES FACULTY(email));

CREATE TABLE PROGRAM
	(gkey VARCHAR(8) NOT NULL,
	positionsOpen INT,
	size INT,
	univerName VARCHAR(40) NOT NULL,
	dname VARCHAR(50) NOT NULL,
	PRIMARY KEY (gkey),
	FOREIGN KEY (univerName) REFERENCES UNIVERSITIES(uName),
	FOREIGN KEY (univerName, dName) REFERENCES DEPARTMENT(unName, dName));

CREATE TABLE RESEARCH_INTERNSHIP
	(programKey VARCHAR(8) NOT NULL,
	appDeadline DATE,
	tuitionWaver BOOLEAN,
	focus VARCHAR(40),
	stipend BOOLEAN,
	email VARCHAR(40) NOT NULL,
	PRIMARY KEY (programKey, focus),
	FOREIGN KEY (programKey) REFERENCES PROGRAM(gkey),
	FOREIGN KEY (email) REFERENCES FACULTY(email));

CREATE TABLE TA_OPTION
	(programKey VARCHAR(8) NOT NULL,
	tuitionWaver BOOLEAN,
	stipend BOOLEAN,
	PRIMARY KEY (programKey),
	FOREIGN KEY (programKey) REFERENCES PROGRAM(gkey));

CREATE TABLE MASTERS
	(mKey VARCHAR(8) NOT NULL,
	credits INT,
	PRIMARY KEY (mKey),
	FOREIGN KEY (mKey) REFERENCES PROGRAM(gkey));

CREATE TABLE MASTERS_PROJECTS
	(mKey VARCHAR(8) NOT NULL,
	project VARCHAR(40),
	PRIMARY KEY (mKey, project),
	FOREIGN KEY (mKey) REFERENCES PROGRAM(gKey));

CREATE TABLE PHD
	(pKey VARCHAR(8) NOT NULL,
	credits INT,
	PRIMARY KEY (pKey),
	FOREIGN KEY (pKey) REFERENCES PROGRAM(gkey));

CREATE TABLE PHD_PROJECTS
	(pKey VARCHAR(8) NOT NULL,
	project VARCHAR(40),
	PRIMARY KEY (pKey, project),
	FOREIGN KEY (pKey) REFERENCES PROGRAM(gKey));